---
- hosts: webservers
  tasks:
  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='qwerty' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='qwerty' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='qwerty' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

  - name: Installime PHP
    command: apt install php php-cgi php-mysqli php-pear php-mbstring php-gettext libapache2-mod-php php-common php-php$
  - name: install pma
    unarchive:
      src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      dest: /var/www/html
      remote_src: yes

  - name: Installime PMA keyring
    command: wget -P /home/sken/ https://files.phpmyadmin.net/phpmyadmin.keyring

  - name: Vahetame PMA kausta omaniku
    file:
      path: /var/www/html/phpmyadmin/
      state: directory
      recurse: yes
      owner: www-data

  - name: Kopeerime config faili
    command: cp /var/www/html/phpmyadmin/config.sample.inc.php /var/www/html/phpmyadmin/config.inc.php

  - name: Anname config.inc.php failile oigused
    command: chmod 660 /var/www/html/phpmyadmin/config.inc.php

  - name: Muudame oiguseid PMA kataloogil
    command: chown -R www-data:www-data /var/www/html/phpmyadmin

  - name: Teeme restarti apache2
    command: systemctl restart apache2
